# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jgui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(1150, 650)
        Widget.setMinimumSize(QtCore.QSize(1150, 650))
        Widget.setMaximumSize(QtCore.QSize(1150, 650))
        Widget.setSizeIncrement(QtCore.QSize(1250, 700))
        self.label = QtWidgets.QLabel(Widget)
        self.label.setGeometry(QtCore.QRect(-50, -20, 1251, 691))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../new_jarvis/img/border.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Widget)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 1111, 611))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../new_jarvis/img/bgf3.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Widget)
        self.label_3.setGeometry(QtCore.QRect(400, 150, 371, 311))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../new_jarvis/img/world1.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(Widget)
        self.label_5.setGeometry(QtCore.QRect(890, 460, 71, 61))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../new_jarvis/img/d2.gif"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Widget)
        self.label_6.setGeometry(QtCore.QRect(830, 490, 71, 71))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../new_jarvis/img/run.gif"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Widget)
        self.label_7.setGeometry(QtCore.QRect(770, 530, 71, 61))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("../new_jarvis/img/d3.gif"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Widget)
        self.label_8.setGeometry(QtCore.QRect(20, 540, 91, 91))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("../new_jarvis/img/d5.gif"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Widget)
        self.label_9.setGeometry(QtCore.QRect(1040, 20, 91, 91))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("../new_jarvis/img/d1.gif"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Widget)
        self.label_10.setGeometry(QtCore.QRect(20, 20, 101, 91))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("../new_jarvis/img/d4.gif"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Widget)
        self.label_11.setGeometry(QtCore.QRect(1040, 540, 91, 91))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("../new_jarvis/img/run.gif"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_4 = QtWidgets.QLabel(Widget)
        self.label_4.setGeometry(QtCore.QRect(920, 60, 211, 511))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../new_jarvis/img/iface5.png"))
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName("label_4")
        self.label_12 = QtWidgets.QLabel(Widget)
        self.label_12.setGeometry(QtCore.QRect(1020, 150, 111, 321))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("../new_jarvis/img/output-onlinegiftools.gif"))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Widget)
        self.label_13.setGeometry(QtCore.QRect(40, 190, 231, 101))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("../new_jarvis/img/fb.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Widget)
        self.label_14.setGeometry(QtCore.QRect(130, 280, 231, 101))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("../new_jarvis/img/fb.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Widget)
        self.label_15.setGeometry(QtCore.QRect(40, 370, 231, 101))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("../new_jarvis/img/fb.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.textBrowser = QtWidgets.QTextBrowser(Widget)
        self.textBrowser.setGeometry(QtCore.QRect(70, 220, 191, 41))
        self.textBrowser.setStyleSheet("background:transparent;\n"
"font: 700 15pt \"Gadugi\";\n"
"margin-top:5px;\n"
"padding-left:2px;\n"
"text-align:center;\n"
"color:white;\n"
"border:none;")
        self.textBrowser.setInputMethodHints(QtCore.Qt.ImhNone)
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Widget)
        self.textBrowser_2.setGeometry(QtCore.QRect(190, 300, 121, 51))
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
"font: 700 15pt \"Gadugi\";\n"
"margin-top:9px;\n"
"text-align:center;\n"
"color:white;\n"
"border:none;")
        self.textBrowser_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_4 = QtWidgets.QTextBrowser(Widget)
        self.textBrowser_4.setGeometry(QtCore.QRect(90, 390, 121, 51))
        self.textBrowser_4.setStyleSheet("background:transparent;\n"
"font: 700 12pt \"Gadugi\";\n"
"margin-top:9.5px;\n"
"text-align:center;\n"
"color:white;\n"
"border:none;")
        self.textBrowser_4.setInputMethodHints(QtCore.Qt.ImhNone)
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.pushButton = QtWidgets.QPushButton(Widget)
        self.pushButton.setGeometry(QtCore.QRect(820, 500, 91, 61))
        self.pushButton.setStyleSheet("\n"
"font: 600 13pt \"Bahnschrift SemiBold SemiConden\";\n"
"border-radius:50px;\n"
"color:white;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_9.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_4.raise_()
        self.label_8.raise_()
        self.label_10.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.textBrowser.raise_()
        self.textBrowser_2.raise_()
        self.textBrowser_4.raise_()
        self.pushButton.raise_()

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.textBrowser.setHtml(_translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gadugi\'; font-size:9pt; font-weight:700; font-style:normal;\">\n"
"<h5 style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Exo\',\'sans-serif\'; font-size:15pt; color:#ffffff;\">Click RUN To Start</span></h5></body></html>"))
        self.textBrowser_2.setMarkdown(_translate("Widget", "**Time**\n"
"\n"
""))
        self.textBrowser_2.setHtml(_translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gadugi\'; font-size:15pt; font-weight:700; font-style:normal;\">\n"
"<p style=\" margin-top:6px; margin-bottom:6px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Time</p></body></html>"))
        self.textBrowser_4.setMarkdown(_translate("Widget", "**Date**\n"
"\n"
""))
        self.textBrowser_4.setHtml(_translate("Widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gadugi\'; font-size:15pt; font-weight:700; font-style:normal;\">\n"
"<p style=\" margin-top:10px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Date</p></body></html>"))
        self.pushButton.setText(_translate("Widget", "RUN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec())
